import Head from 'next/head';
import GetStarted from '../components/Home/GetStarted';

import Hero from '../components/Home/Hero';
import Navbar from '../components/Navbar';

export default function Home() {
	return (
		<div>
			<Head>
				<title>OnPoint</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<link rel='icon' href='/Logo.svg' />
			</Head>
			<main>
				<Navbar />
				<Hero />
				<GetStarted />
			</main>
		</div>
	);
}
