import Head from 'next/head';

import Hero from '../components/Hero';
import Navbar from '../components/Navbar';

export default function Home() {
	return (
		<div>
			<Head>
				<title>OnPoint</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<link rel='icon' href='/Logo.svg' />
			</Head>
			<main
				style={{
					backgroundColor: 'black'
				}}
			>
				<Navbar />
				<Hero />
			</main>
		</div>
	);
}
